### ISSUE TITLE
On Precompile assets line of the Dockerfile..

### ISSUE THREAD

**Issue by armbox** [staannoe/tracks#1]
**RAILS_ENV=production** is missed.(Just after initialize the database)
So in the tracks application one can't see the images.

Cloud you update the Dockerfile?

Thanks,

**Comment by staannoe** [comment]
Sorry for the late response, your request has somehow passed me unnoticed (until now).

I have updated the Dockerfile.
Thanks for your diagnose, it was spot on.

Kind regards
Stig
