### ISSUE TITLE
docker stop | docker start

### ISSUE THREAD

**Issue by webdawg** [staannoe/tracks#2]
after issueing a docker stop

it will not docker start again

**Comment by staannoe** [comment]
Can you please provide me with the output of:
`# docker logs <your container name>`

Regards
Stig

**Comment by webdawg** [comment]
I would think the relevent lines would be:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
httpd (pid 13) already running

**Comment by webdawg** [comment]
I upgraded dockerize to see if it would do anything and the container would exit right after the same message.  I am trying to figure out how to fix too.

**Comment by webdawg** [comment]
root@4f01d4cd8bb7:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4448   744 ?        Ss   17:01   0:00 /bin/sh -c "doc
root         5  0.0  0.1   7128  2396 ?        Sl   17:01   0:00 dockerize -stdo
root        15  0.4  0.1  18144  3224 ?        Ss   17:05   0:00 bash
root        33  0.0  0.1  15572  2116 ?        R+   17:05   0:00 ps aux

I am about to delete the pid and restart

**Comment by webdawg** [comment]
rm /run/apache2/apache2.pid

That did it.

root@hsl-intranet:~# docker exec -it 4f01d4cd8bb7 bash
root@4f01d4cd8bb7:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.0   4448   680 ?        Ss   17:08   0:00 /bin/sh -c "doc
root         5  0.0  0.1   7128  2396 ?        Sl   17:08   0:00 dockerize -stdo
root         8  0.0  0.0   4448   780 ?        S    17:08   0:00 /bin/sh /usr/sb
root        12  0.1  0.3  84456  6792 ?        S    17:08   0:00 /usr/sbin/apach
root        35  0.0  0.1 223200  3500 ?        Ssl  17:08   0:00 PassengerWatchd
root        38  0.0  0.1 504252  3804 ?        Sl   17:08   0:00 PassengerHelper
nobody      43  0.0  0.4 239808  8648 ?        Sl   17:08   0:00 PassengerLoggin
www-data    53  0.0  0.2 371484  4380 ?        Sl   17:08   0:00 /usr/sbin/apach
www-data    54  0.0  0.2 371484  4380 ?        Sl   17:08   0:00 /usr/sbin/apach
root       113  3.5  0.1  18148  3176 ?        Ss   17:08   0:00 bash
root       128  0.0  0.1  15572  2108 ?        R+   17:08   0:00 ps aux

**Comment by webdawg** [comment]
https://github.com/docker-library/php/blob/master/7.0/apache/apache2-foreground

**Comment by staannoe** [comment]
Yes, I suspected it since I have seen the same behavior on other containers, but haven't experienced it on this one until you did. Implemented your fix.

tnx

Kind regards
Stig
