### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by webdawg** [staannoe/tracks#3]
For production use it is highly recommended to update the site.yml.template within the build repo, rename it to site.yml then rebuild the container.

Can you explain to me what this means?

**Comment by staannoe** [comment]
Hi,

First off, thanks for your contribution, i've tested and merged today.

I strongly recommend updating the "secret_token" value in the site.yml. This is a security issue, if you use the default value, well it isn't random as it should be.

Kind regards
Stig
